package modelo;

public enum StatusTelaUsuario {

	VALORESNULOS ,INCLUIR, LISTAR, EDITAR, EXCLUIR,   FUNCIONARIEDITADO, ERROAOEDITAROFUNCIONARIO, FUNCIONARIOCADASTRADO, ERROCADASTROFUNCIONARIO, NAOEXIBIRMENSSAGEM, FUNCIONARIOJACADASTRADO, USUARIOJAEXISTENTE,

	//Endereco
	 ENDERECOCADASTRADO, ERROCADASTRARENDERECO, ENDERECOALTERADO, ERROALTERARENDERECO, ENDERECOCORRETO ,
	 
	 
	 
	 //Usuario
	 USUARIOEXISTENTE, USUARIONAOCADASTRADO, USUARIONAOEXISTENTE,

	 // Cliente
	 CLIENTECADASTRADO, ERROCADASTROCLIENTE,CLIENTENAOEXISTENTE,ERROALTERARCLIENTE,CLIENTELTERADO,
	 
	 //TODOS
	 CPFEXISTENTE;
	
}
